name: Deploy Pages (resolve LFS)
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: |
          git lfs install
          git lfs pull
      - run: |
          mkdir -p dist
          cp -r DalseoHankyeon_Test/* dist/
          touch dist/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4