name: Deploy Pages (resolve LFS)
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }     # LFS 객체를 실파일로 체크아웃
      - run: |
          git lfs install
          git lfs pull
          touch DalseoHankyeon_Test/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: DalseoHankyeon_Test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4